Fixed test verification not failing with error (#6)

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -32,6 +32,8 @@ jobs:
           github-token: ${{ secrets.GITHUB_TOKEN }}
 
       - name: Verify
+        env:
+          TEST_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
           GIT_USER_NAME=$(git config --get user.name)
           if [[ "$GIT_USER_NAME" != "GitHub Actions" ]]
@@ -48,9 +50,15 @@ jobs:
           fi
 
           GIT_REMOTE_URL=$(git remote get-url origin)
-          if [[ "$GIT_REMOTE_URL" != https://github-actions[bot]:${{ secrets.GITHUB_TOKEN }} ]]
+          if [[ ! "$GIT_REMOTE_URL" =~ ^'https://github-actions[bot]' ]]
           then
-            echo "::error::Expected git remote url to have login and token but got '$GIT_REMOTE_URL'"
+            echo "::error::Expected git remote url to have login but got '$GIT_REMOTE_URL'"
+            exit 1
+          fi
+          if [[ ! "$GIT_REMOTE_URL" =~ ^'https://github-actions[bot]:'"$TEST_TOKEN" ]]
+          then
+            echo "::error::Expected git remote url to have token but got '$GIT_REMOTE_URL'"
+            exit 1
           fi
 
   test-with-user-app-installation-token:
@@ -82,6 +90,8 @@ jobs:
           github-token: ${{ steps.get-github-app-token.outputs.token }}
 
       - name: Verify
+        env:
+          TEST_TOKEN: ${{ steps.get-github-app-token.outputs.token }}
         run: |
           GIT_USER_NAME=$(git config --get user.name)
           if [[ "$GIT_USER_NAME" != "Check Git Status Bot" ]]
@@ -98,9 +108,15 @@ jobs:
           fi
 
           GIT_REMOTE_URL=$(git remote get-url origin)
-          if [[ "$GIT_REMOTE_URL" != https://check-git-status-bot[bot]:${{ secrets.GITHUB_TOKEN }} ]]
+          if [[ ! "$GIT_REMOTE_URL" =~ ^'https://check-git-status-bot[bot]' ]]
           then
             echo "::error::Expected git remote url to have login and token but got '$GIT_REMOTE_URL'"
+            exit 1
+          fi
+          if [[ ! "$GIT_REMOTE_URL" =~ ^'https://check-git-status-bot[bot]:'"$TEST_TOKEN" ]]
+          then
+            echo "::error::Expected git remote url to have token but got '$GIT_REMOTE_URL'"
+            exit 1
           fi
 
   test-with-repo-app-installation-token:
@@ -131,6 +147,8 @@ jobs:
           github-token: ${{ steps.get-github-app-token.outputs.token }}
 
       - name: Verify
+        env:
+          TEST_TOKEN: ${{ steps.get-github-app-token.outputs.token }}
         run: |
           GIT_USER_NAME=$(git config --get user.name)
           if [[ "$GIT_USER_NAME" != "Check Git Status Bot" ]]
@@ -147,9 +165,15 @@ jobs:
           fi
 
           GIT_REMOTE_URL=$(git remote get-url origin)
-          if [[ "$GIT_REMOTE_URL" != https://check-git-status-bot[bot]:${{ secrets.GITHUB_TOKEN }} ]]
+          if [[ ! "$GIT_REMOTE_URL" =~ ^'https://check-git-status-bot[bot]' ]]
           then
             echo "::error::Expected git remote url to have login and token but got '$GIT_REMOTE_URL'"
+            exit 1
+          fi
+          if [[ ! "$GIT_REMOTE_URL" =~ ^'https://check-git-status-bot[bot]:'"$TEST_TOKEN" ]]
+          then
+            echo "::error::Expected git remote url to have token but got '$GIT_REMOTE_URL'"
+            exit 1
           fi
 
   test-with-classic-personal-access-token:
@@ -171,6 +195,8 @@ jobs:
           github-token: ${{ secrets.CLASSIC_PERSONAL_ACCESS_TOKEN }}
 
       - name: Verify
+        env:
+          TEST_TOKEN: ${{ steps.get-github-app-token.outputs.token }}
         run: |
           GIT_USER_NAME=$(git config --get user.name)
           if [[ "$GIT_USER_NAME" != "Cat Chen" ]]
@@ -187,7 +213,13 @@ jobs:
           fi
 
           GIT_REMOTE_URL=$(git remote get-url origin)
-          if [[ "$GIT_REMOTE_URL" != https://CatChen:${{ secrets.GITHUB_TOKEN }} ]]
+          if [[ ! "$GIT_REMOTE_URL" =~ ^'https://CatChen' ]]
           then
             echo "::error::Expected git remote url to have login and token but got '$GIT_REMOTE_URL'"
+            exit 1
+          fi
+          if [[ ! "$GIT_REMOTE_URL" =~ ^'https://CatChen:'"$TEST_TOKEN" ]]
+          then
+            echo "::error::Expected git remote url to have token but got '$GIT_REMOTE_URL'"
+            exit 1
           fi
